language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.0
env:
  - sshkit="master"
  - sshkit="= 1.7.1"
  - sshkit="= 1.6.1"
matrix:
  include:
    # Run Danger only once, on 2.3.1
    - rvm: 2.3.1
      before_script: bundle exec danger

before_install: gem install bundler --conservative --version '~> 1.10'
